### ISSUE TITLE
File line encoding issue with sass-loader on Windows

### ISSUE THREAD

**Issue by phev8** [influenzanet/study-manager-app#12]
As @Infectieradar reported, there are some issues when calling `yarn start`, complaining about end of line character issues. The problem is observed on Windows machines. 

```
Error: resolve-url-loader: CSS error
  source-map information is not available at url() declaration (found orphan CR, try removeCR option)
```

![image001](https://user-images.githubusercontent.com/13927969/104610633-96c38580-5684-11eb-8865-b69de0c993be.png)

@yannickvandendijck do you have this as well?

**Comment by phev8** [comment]
We have found some discussions mentioning similar issues. Based on these it seems git converts the line endings when checking out the repository.

https://github.com/desktop/desktop/issues/10666
https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf

**Comment by phev8** [comment]
On my Windows VM I could reproduce the issue. Following steps helped me solve this:

1. I was on the `master` branch when opening Github Desktop -> Menu: Repository / Open In Command Prompt
<img width="668" alt="Screenshot 2021-01-14 at 16 20 12" src="https://user-images.githubusercontent.com/13927969/104611868-e060a000-5685-11eb-8bfc-470c9c80e9f9.png">

2. Type `git config core.autocrlf` to check the current value for the corresponding setting. By default this was set to "true" on my system.
3. Type `git config core.autocrlf false` changes this value to false. (With step 2, you can check the new value if was set properly.) This setting would prevent git overriding the end of lines in the files when checking them out.
4. On my system, it caused a lot of file changes in git (basically replaced the line ends of every file in the repo). Then I selected all the changes and clicked "Discard". 
<img width="264" alt="Screenshot 2021-01-14 at 16 35 34" src="https://user-images.githubusercontent.com/13927969/104612482-890eff80-5686-11eb-864b-d0ee3534b337.png">
5. Switched to the dev branch - and then with `yarn start` the project worked as expected. 

@Infectieradar could you please try if this also helps to solve your issues.

**Comment by yannickvandendijck** [comment]
I didn't have this problem up to now. 
However, I only worked with the dev brach until now.

**Comment by phev8** [comment]
The dev branch was also effected, so it must be something different. 
Did you launch with `yarn start` and you can see the preview? (If yes, that's great, just want to understand in what cases this happens) Are you using it on Windows 10?

**Comment by yannickvandendijck** [comment]
Yes, I launch with yarn start and able to see the preview.
No, It is an older machine running Windows 8.

**Comment by Infectieradar** [comment]
@phev8 I just tested your solution for the yarn problem, and it worked! Yarn is however incredibly slow, have to wait for almost 10 minutes for the questionnaire to appear...but it works!
