### ISSUE TITLE
Export prettified json

### ISSUE THREAD

**Issue by m-delfino** [influenzanet/study-manager-app#132]
It would be nice if we could generate prettified json and eventually compact it just before uploading the survey to the server using `admin-scripts`. It would be much easier to track changes.

**Comment by phev8** [comment]
Good idea.
Minifying also has very little impact probably, since it's only sometimes when you upload and after the api gateway it is converted to the internal format anyways.

**Comment by phev8** [comment]
Added the whitespaces for the JSON export on the dev branch.
