### ISSUE TITLE
Add open text field for an 'other' option

### ISSUE THREAD

**Issue by yannickvandendijck** [influenzanet/study-manager-app#18]
Is it possible to add an open text field when a participant selects a certain option. For example, if the option 'Other' would be chosen below? It should be optional for the participant to complete the open text field.
![image](https://user-images.githubusercontent.com/34121959/104742912-54b14700-574b-11eb-80f9-3f5c31c22229.png)

**Comment by phev8** [comment]
Yes, it is possible.

For the corresponding response option, you only need to change the `role` attribute from `option` to `input`.

You can use the `content` attribute for the text before the textfield, and with the `description` attribute you can control if the text input should have placeholder text. The description is defined exactly the same way as the content.

**Comment by phev8** [comment]
@yannickvandendijck I put an example into your intake file. I hope it's ok, otherwise you can revert it. 

The `content` and `description` are optional, you can remove them if you want. The `style` attribute adds the css class responsible that it will take up the whole line.

```
...
{
            key: '4', role: 'input',
            disabled: expWithArgs('responseHasKeysAny', editor.getItem().key, responseGroupKey + '.' + multipleChoiceKey, '0'),
            style: [{ key: 'className', value: 'w-100' }],
            content: new Map([
                ["nl-be", "Ik volg een ander dieet"],
            ]),
            description: new Map([
                ["nl-be", "dieet"],
            ])
        },
...
```

**Comment by phev8** [comment]
Closing the issue for now, feel free to reopen if necessary.

**Comment by LisaHermans** [comment]
![image](https://user-images.githubusercontent.com/71076574/105988111-7db4ce80-609f-11eb-9b13-d698d010f306.png)

How can we change this: the text (Ik volg een ander dieet) in one line, so no line break between 'ander' and 'dieet'.
