### ISSUE TITLE
Dropdown menu with text behind the box + min/max dropdown menu

### ISSUE THREAD

**Issue by LisaHermans** [influenzanet/study-manager-app#22]
1) I would like to program a dropdown menu with the word 'days' after the dropdown box. 
This code does not do the trick:
       {
            key: '1', role: 'numberInput',
            //properties:{min:0,max:14},
            description: new Map([
                ["nl-be", "Dagen"],
                ["fr-be","Jours"],
                ["de-be","Tage"],
                ["en-be","Days"],
            ])

How should I program this?

2) What is the correct line to add a minimum and maximum value to the dropdown menu?

**Comment by phev8** [comment]
Dropdown menu would be a different topic, but to use the numeric input, with min and max you can use the following snippet:

```
{
            key: '1', role: 'numberInput',
            optionProps: {
                min: { dtype: 'num', num: 0 },
                max: { dtype: 'num', num: 14 },
            },
            content: new Map([
                ["nl-be", "Dagen"],
            ]),
            description: new Map([
                ["nl-be", "Placeholder"],
            ]),
            style: [
                { key: 'labelPlacement', value: 'after' }
            ]
        },
```

We also added the option to place the label after the input field. If that style is not defined, it will be before the label. The description attribute is used as a placeholder when value is intentionally removed by the user.

<img width="652" alt="Screenshot 2021-02-07 at 14 15 40" src="https://user-images.githubusercontent.com/13927969/107147634-57204e80-694f-11eb-820e-254b60bae4a9.png">
