### ISSUE TITLE
Submit survey with empty multiple choice questions

### ISSUE THREAD

**Issue by yannickvandendijck** [influenzanet/study-manager-app#31]
I encountered an issue that you could submit a questionnaire when a multiple-choice question has no ticked answer. This can happen when:

- You select a certain answer in a multiple choice question
- Then you unselect that same answer (and thus the multiple choice question has no valid answer anymore)
- Now submitting the questionnaire can be done even that no valid answer is selected for the multiple choice question

Thus suppose I would have this:
![image](https://user-images.githubusercontent.com/34121959/110649894-554de300-81ba-11eb-810c-a72fdf0db342.png)

Then I unselect again 'Chills'
![image](https://user-images.githubusercontent.com/34121959/110649964-672f8600-81ba-11eb-8aa8-657e8df1040f.png)

I am able now to submit the questionnaire eventhough the symptoms questions is empty and thus without valid responses.

**Comment by phev8** [comment]
Thank you for reporting the issue. 
With the recent commit on the dev-branch this issue should be fixed here in the study-manager. (Web-app will receive the fix, with one of the following updates as well.)
