### ISSUE TITLE
Survey selector: instance and language code

### ISSUE THREAD

**Issue by yannickvandendijck** [influenzanet/study-manager-app#9]
Peter,
When running 'yarn start' we are getting the survey selector.
When choosing 'instance: Bel' and language Nederlands --> we are not seeing the "nl-be" inputs, but it remains the "nl" inputs.
Can this be changed?

**Comment by phev8** [comment]
Yes, will fix it. 
I think best is to have a list of supported languages per instance - so when you select 'Bel' - you would see the languages that are relevant for you.

**Comment by phev8** [comment]
Language selector logic was improved with the latest commit -> 5fb6e68
